import VerusLean.VLIR.Elab
import Lean.PrettyPrinter
import Lean.Elab.Command
import Lean.Util.SearchPath

namespace VerusLean

open Lean PrettyPrinter

private def warningComment : String := String.intercalate "\n" <| [
  "/-",
  "  ------------------------------------------------------------------------------",
  "  This file was automatically generated by the Verus-Lean pipeline.",
  "  YOU MAY LOSE WORK IF YOU RUN THE PIPELINE AGAIN TO RE-GENERATE THIS FILE.",
  "  Read this comment carefully to avoid this situation.",
  "",
  "  The Verus-Lean pipeline translates Verus definitions and verification",
  "  conditions into Lean code. If a Lean file of the same name already",
  "  exists, then the pipeline attempts to update the existing definitions",
  "  and theorem statements while leaving the rest of the file alone.",
  "",
  "  Translated/updated theorem statements are tagged with a MAGIC comment.",
  "  For best results, leave these comments alone, and don't change",
  "  the theorem statement.",
  "  (Definitions always get overwritten.)",
  "",
  "  For more information about how the pipeline works, see [THIS FILE].",
  "  ------------------------------------------------------------------------------",
  "-/",
]

private def pipelineGenComment : String := String.intercalate "\n" <| [
  "/- Auto-generated. Don't edit (proofs are okay). MAGIC COMMENT END -/",
]

private def imports : List String := [
  "VerusLean.Basic",
  "VerusLean.Tactic.ByVerus",
  "VerusLean.Vstd",
]

private def preludeString (nameSpace : String) := String.intercalate "\n" <|
  (imports.map (s!"import {·}")) ++ [
  "",
  warningComment,
  "",
  "namespace VerusLean",
  "",
  s!"namespace {nameSpace}",
  "",
  "/- Prelude done. Place all declarations below. MAGIC COMMENT END. -/"
]

private def postludeString (nameSpace : String) := String.intercalate "\n" <| [
  s!"end {nameSpace} /- namespace -/",
  "",
  "end VerusLean",
]

--------------------------------------------------------------------------------

/-
  Attempts to take a list of `Decl`s, sorted with the spec functions first
  and the theorems/assertions last, and performs delaboration.

  Delaboration proceeds by adding prior definitions to the context/environment,
  just to ensure that everything type-checks.

  TODO: Support mutually-recursive functions
  TODO: Set the namespace to be `VerusLean` to prevent clash with e.g. `factorial` or `add`
    (CC: I think we're okay for most things, but root-level functions like `max`
         could be problematic.)
-/
unsafe def Decl.toFormat (ns : String) (defs thms : List Decl) : IO (Except String String) := do
  -- CC: Supposedly `c_t_s_p` is deprecated, so we manually include the library
  -- CC: This is *incredibly* brittle, and assumes the executable doesn't move
  -- CC: Might also need `././.lake/packages/batteries/.lake/build/lib/lean`
  -- searchPathRef.set compile_time_search_path%  -- (old version)
  searchPathRef.set [s!"{(← findSysroot)}/lib/lean", ".lake/build/lib/lean"]
  let res : Except Exception Format ← Lean.withImportModules
    (imports := #[{ module := `Init }, { module := `VerusLean.Basic },
                  { module := `VerusLean.Vstd }, { module := `VerusLean.Tactic.ByVerus }])
    (opts := Options.empty)
    (trustLevel := 0)
    (fun env => EIO.toIO' <|
      Core.CoreM.run'
        (ctx := {
          fileName := ""
          fileMap := default
          currNamespace := String.toName ns
        })
        (s := { env })
        (do
          try
            -- Convert the `Decl`s into Lean `Term`s, store the syntax
            let specDefs := defs.filter Decl.shouldInclude
            let specSyns ← specDefs.mapM (·.toTerm)

            let thms := thms.filter Decl.shouldInclude
            let thmSyns ← thms.mapM (·.toTerm)

            /-
              Now add the `Term`s into the meta-context to ensure that
              they type-check.

              This block of code doesn't actually extract any printable strings,
              but it acts as a good sanity check that things are okay.

              Note: Wojciech claims that lifting into `CommandElabM` multiple
              times causes bad things to happen, so do it only once.
            -/
            /- let _ ← Lean.liftCommandElabM <| (do
              let _ ← specSyns.mapM (Elab.Command.elabCommandTopLevel ·.raw)
              let _ ← userSyns.mapM (Elab.Command.elabCommandTopLevel ·.raw)
              thmSyns.mapM (Elab.Command.elabCommandTopLevel ·.raw)
            ) -/

            /-
              Now ask Lean for a pretty-printed version of the command syntax.
              This part is untrusted, in the sense that this can return
              bad Lean syntax (i.e., syntax that doesn't compile).
              However, the block above should prevent this from happening.
            -/
            let mut fmt : Format := (preludeString ns) ++ .line
            for syns in [specSyns, thmSyns] do
              for syn in syns do
                fmt := fmt ++ .line ++ pipelineGenComment ++ .line ++ (
                  ← format (Formatter.categoryFormatter `command) syn
                ) ++ .line

            return fmt ++ .line ++ (postludeString ns) ++ .line
          catch e =>
            dbg_trace s!"{← e.toMessageData.toString}"
            throw e
        )
    )

  match res with
  | .error _ => return throw "bad syntax"
  | .ok res => return (return Std.Format.pretty res)

end VerusLean
