import VerusLean.VLIR.Elab
import Lean.PrettyPrinter
import Lean.Elab.Command
import Lean.Util.SearchPath

namespace VerusLean

open Lean PrettyPrinter

private def warningComment : String := String.intercalate "\n" <| [
  "/-",
  "  ------------------------------------------------------------------------------",
  "  This file was automatically generated by the Verus-Lean pipeline.",
  "  YOU MAY LOSE WORK IF YOU RUN THE PIPELINE AGAIN TO RE-GENERATE THIS FILE.",
  "  Read this comment carefully to avoid this situation.",
  "",
  "  The Verus-Lean pipeline generates two sections, in this order:",
  "",
  "      1. Data structures and Verus spec functions",
  "      2. Spec theorem statements",
  "",
  "  These sections are clearly marked with comment blocks similar to this one.",
  "  DO NOT EDIT SECTION (1). It gets entirely overwritten by the pipeline.",
  "",
  "  It is okay to edit section (2), as long as you don't change the theorem",
  "  statements. If the corresponding Verus file changes, then the pipeline will",
  "  update the theorem statements and leave a MAGIC comment with the old theorem",
  "  statement, for your reference. The pipeline leaves proofs alone.",
  "",
  "  For more information about how the pipeline works, see [THIS FILE].",
  "  ------------------------------------------------------------------------------",
  "-/",
]

private def sectionStart (sec : String) (canEdit : Bool) : String :=
  if canEdit then
    s!"/- Section {sec}. MAGIC COMMENT END -/"
  else
    s!"/- Section {sec}. DO NOT EDIT THIS SECTION. MAGIC COMMENT END -/"

private def sectionEnd (sec : String) (canEdit : Bool) : String :=
  if canEdit then
    s!"/- End section {sec}. MAGIC COMMENT END -/"
  else
    s!"/- End section {sec}. DO NOT EDIT THIS SECTION. MAGIC COMMENT END -/"

private def defsSectionStr := "(1) Definitions"
private def defsSectionStart := sectionStart defsSectionStr false
private def defsSectionEnd := sectionEnd defsSectionStr false

private def userThmsSectionStr := "(2) User theorem statements"
private def userThmsSectionStart := sectionStart userThmsSectionStr true
private def userThmsSectionEnd := sectionEnd userThmsSectionStr true

private def specThmsSectionStr := "(2) Spec theorems"
private def specThmsSectionStart := sectionStart specThmsSectionStr true
private def specThmsSectionEnd := sectionEnd specThmsSectionStr true

private def imports : List String := [
  "VerusLean.Basic",
  "VerusLean.Tactic.ByVerus",
  "VerusLean.Vstd",
]

private def preludeString (nameSpace : String) := String.intercalate "\n" <|
  (imports.map (s!"import {·}")) ++ [
  "",
  warningComment,
  "",
  "namespace VerusLean",
  "",
  s!"namespace {nameSpace}",
  "",
]

private def postludeString (nameSpace : String) := String.intercalate "\n" <|
  [
  s!"end {nameSpace} /- namespace -/",
  "",
  "end VerusLean",
]

--------------------------------------------------------------------------------

/-
  Attempts to take a list of `Decl`s, sorted with the spec functions first
  and the theorems/assertions last, and performs delaboration.

  Delaboration proceeds by adding prior definitions to the context/environment,
  just to ensure that everything type-checks.

  TODO: Support mutually-recursive functions
  TODO: Set the namespace to be `VerusLean` to prevent clash with e.g. `factorial` or `add`
    (CC: I think we're okay for most things, but root-level functions like `max`
         could be problematic.)
-/
unsafe def Decl.toFormat (ns : String) (defs thms : List Decl) : IO (Except String String) := do
  -- CC: Supposedly `c_t_s_p` is deprecated, so we manually include the library
  -- CC: This is *incredibly* brittle, and assumes the executable doesn't move
  -- CC: Might also need `././.lake/packages/batteries/.lake/build/lib/lean`
  -- searchPathRef.set compile_time_search_path%  -- (old version)
  searchPathRef.set [s!"{(← findSysroot)}/lib/lean", ".lake/build/lib/lean"]
  let res : Except Exception Format ← Lean.withImportModules
    (imports := #[{ module := `Init }, { module := `VerusLean.Basic },
                  { module := `VerusLean.Vstd }, { module := `VerusLean.Tactic.ByVerus }])
    (opts := Options.empty)
    (trustLevel := 0)
    (fun env => EIO.toIO' <|
      Core.CoreM.run'
        (ctx := {
          fileName := ""
          fileMap := default
          currNamespace := String.toName ns
        })
        (s := { env })
        (do
          try
            -- Convert the `Decl`s into Lean `Term`s, store the syntax
            let specDefs := defs.filter Decl.shouldInclude
            let specSyns ← specDefs.mapM (·.toTerm)

            let thms := thms.filter Decl.shouldInclude
            let thmSyns ← thms.mapM (·.toTerm)

            /-
              Now add the `Term`s into the meta-context to ensure that
              they type-check.

              This block of code doesn't actually extract any printable strings,
              but it acts as a good sanity check that things are okay.

              Note: Wojciech claims that lifting into `CommandElabM` multiple
              times causes bad things to happen, so do it only once.
            -/
            /- let _ ← Lean.liftCommandElabM <| (do
              let _ ← specSyns.mapM (Elab.Command.elabCommandTopLevel ·.raw)
              let _ ← userSyns.mapM (Elab.Command.elabCommandTopLevel ·.raw)
              thmSyns.mapM (Elab.Command.elabCommandTopLevel ·.raw)
            ) -/

            /-
              Now ask Lean for a pretty-printed version of the command syntax.
              This part is untrusted, in the sense that this can return
              bad Lean syntax (i.e., syntax that doesn't compile).
              However, the block above should prevent this from happening.
            -/
            let mut fmt : Format := (preludeString ns) ++ .line ++ .line
            for (s, e, syns) in
              [(defsSectionStart, defsSectionEnd, specSyns),
              (specThmsSectionStart, specThmsSectionEnd, thmSyns)] do

              fmt := fmt ++ s ++ .line
              for syn in syns do
                fmt := fmt ++ .line ++ (
                  ← format (Formatter.categoryFormatter `command) syn
                ) ++ .line
              fmt := fmt ++ .line ++ e ++ .line ++ .line ++ .line

            return fmt ++ (postludeString ns) ++ .line
          catch e =>
            dbg_trace s!"{← e.toMessageData.toString}"
            throw e
        )
    )

  match res with
  | .error _ => return throw "bad syntax"
  | .ok res => return (return Std.Format.pretty res)

end VerusLean
