import VerusLean.Tactic.Modular.Poly.Monomial
import VerusLean.Tactic.Modular.Poly.Poly
import VerusLean.Tactic.Modular.Poly.MTerm


/-!

  Dox go here.

-/

#exit


namespace HPoly

partial def buchbergers (ps : Array Polynomial) (cmp : MOrder := Monomial.grevlexOrder) : Array HPoly :=
  -- Transform polynomials into history annotated ones
  let hPolys := ps.mapIdx (λ i p => HPoly.mk p (History.basis i)) |>.map normalize

  let rec loop (i j checked len : Nat) (hij : i < j) (basis : Array HPoly) (h_len : len ≤ basis.size) :=
    if hi : i < len then
      if hj : j < len then
        match sPoly' basis i j (by omega) (by omega) cmp with
        | .inl _ => loop i (j + 1) checked len (by omega) basis h_len
        | .inr ⟨s, sHist⟩ =>
          dbg_trace s!"div-ing (hpoly) {s}"
          let ⟨subBasis, subBasisHist⟩ := takeSplit basis len (by omega)
          match divPolys ⟨s, sHist⟩ (basis.take len) cmp with
          | (qs, ⟨rem, remHist⟩) =>
            if rem.size ≠ 0 then
              let remNormalized := normalize ⟨rem, remHist⟩
              loop i (j + 1) checked len (by omega) (basis.push remNormalized)
                (by simp [Array.size_push]; exact Nat.le_succ_of_le h_len)
            else
              loop i (j + 1) checked len (by omega) basis h_len
      else
        let i' := i + 1
        let j' := max (i' + 1) checked
        loop i' j' checked len (by omega) basis h_len
    else
      if h_len' : len ≥ basis.size then
        basis
      else
        let checked' := len
        let i' := 0
        let j' := max (i' + 1) checked'
        let len' := basis.size
        loop i' j' checked' len' (by omega) basis (Nat.le_refl _)

  let basisRes := loop 0 1 0 0 (by omega) hPolys (Nat.zero_le _)
  minimizeBasis basisRes

def constructWitness (n : Nat) (h : History) (cmp : MOrder) : Array Polynomial :=
  let zeros : Array Polynomial := Array.mkArray n 0
  have h_zeros : zeros.size = n := by
    simp only [Array.size_mkArray, zeros]
  let one : Polynomial := #[MTerm.mk 1 0]

  let rec loop : History → ({ arr : Array Polynomial // arr.size = n })
    | .zero => ⟨zeros, h_zeros⟩

    | .basis i =>
      if hi : i < n then
        let w := zeros.set i one
        ⟨w, by simp [w, h_zeros]⟩
      else
        dbg_trace s!"panic! {n} {i}"
        ⟨zeros, h_zeros⟩

    | .scalarMul c h =>
      match loop h with
      | ⟨w, hw⟩ =>
        let t : MTerm := MTerm.mk c 0
        let w' : Array Polynomial := w.map (λ p => t * p)
        ⟨w', by simp [w']; exact hw⟩

    | .termMul t h =>
      match loop h with
      | ⟨w, hw⟩ =>
        let w' : Array Polynomial := w.map (λ p => t * p)
        ⟨w', by simp [w']; exact hw⟩

    | .addHist h₁ h₂ =>
      let ⟨w₁, hw₁⟩ := loop h₁
      let ⟨w₂, hw₂⟩ := loop h₂
      let w := w₁.zipWith w₂ (Polynomial.add · · cmp)
      ⟨w, by simp [w, hw₁, hw₂]⟩

    | .subHist h₁ h₂ =>
      let ⟨w₁, hw₁⟩ := loop h₁
      let ⟨w₂, hw₂⟩ := loop h₂
      let w := w₁.zipWith w₂ (Polynomial.sub · · cmp)
      ⟨w, by simp [w, hw₁, hw₂]⟩

  loop h


-- Returns `true` if `p` lies in the ideal generated by `ps`.
-- TODO: Later, return the witness.
partial def idealMembership (p : Polynomial) (ps : Array Polynomial)
    (cmp : MOrder := Monomial.grevlexOrder) : (Unit ⊕ Array Polynomial) :=
  let n := ps.size
  let basis := buchbergers ps
  let printStr := basis.foldl (init := "[\n") (λ str hp => str ++ s!" {hp},\n")
  dbg_trace s!"returned basis: {printStr}]"
  let (_, ⟨rem, remHist⟩) := divPolys (HPoly.mk p (History.basis n)) basis cmp
  if rem.size = 0 then
    match remHist with
    | .subHist h₁ h₂ =>
      match h₁ with
      | .basis n =>
        -- Calculate the Array witness in terms of the basis,
        -- which are themselves historied in terms of the original basis polynomials
        dbg_trace s!"Rem is zero, history is {h₂}"
        Sum.inr <| constructWitness n h₂ cmp
      | _ => panic! "LHS of sub isn't right"
    | _ => panic! "Shape of history is wrong for rem of 0"
  else
    Sum.inl ()

end HPoly

----------------------------

-- Example from page 90 of Ideals book

--    x³ - 2xy
def p₁ : Polynomial := #[MTerm.mk 1 #[3, 0], MTerm.mk (-2) #[1, 1]]
#eval p₁.toString

--    x²y - 2y² + x
def p₂ : Polynomial := #[MTerm.mk 1 #[2, 1], MTerm.mk (-2) #[0, 2], MTerm.mk 1 #[1, 0]]
#eval p₂.toString

--     x²
def p_mem : Polynomial := #[MTerm.mk 1 #[2, 0]]

-- Expected: #[x1^2, x1 * x2, x2^2 - 1/2 x1]
#eval Polynomial.buchbergers #[p₁, p₂]
#eval HPoly.buchbergers #[p₁, p₂] |>.map (fun | .mk p _ => p)

-- Expected: [-x2, x1], since   x² = (-y) (x³ - 2xy) + (x) (x²y - 2y² + x)
#eval HPoly.idealMembership p_mem #[p₁, p₂]
#eval timeit "time elapsed" do
  match HPoly.idealMembership p_mem #[p₁, p₂] with
  | .inl () => IO.println "No witness found"
  | .inr w =>
    let wStr := w.foldl (init := "[\n") (λ str p => str ++ s!" {p},\n")
    IO.println s!"Witness found: {wStr}]"
  return ()

----------------------------

-- Example from John Harrison's paper

-- On variables [a, d, n, u, v, x, y]

--      ay - ax - dn
def p₃ : Polynomial := #[MTerm.mk 1 #[1, 0, 0, 0, 0, 0, 1], MTerm.mk (-1) #[1, 0, 0, 0, 0, 1, 0], MTerm.mk (-1) #[0, 1, 1, 0, 0, 0, 0]]

--      au + nv - 1
def p₄ : Polynomial := #[MTerm.mk 1 #[1, 0, 0, 1, 0, 0, 0], MTerm.mk 1 #[0, 0, 1, 0, 1, 0, 0], MTerm.mk (-1) #[0, 0, 0, 0, 0, 0, 0]]

--      n
def p₅ : Polynomial := #[MTerm.mk 1 #[0, 0, 1, 0, 0, 0, 0]]

--      y - x
def p₆ : Polynomial := #[MTerm.mk (-1) #[0, 0, 0, 0, 0, 1, 0], MTerm.mk 1 #[0, 0, 0, 0, 0, 0, 1]]

/-
  The answer/certificate that Harrison provides is

    ( u,    x - y,      ud + vy - vx),

  which translates to

    #[x4, x6 - x7, x2 * x4 + x5 * x7 - x5 * x6]

-/
#eval Polynomial.buchbergers #[p₃, p₄, p₅]
#eval HPoly.idealMembership p₆ #[p₃, p₄, p₅]

#eval timeit "time elapsed" do
  match HPoly.idealMembership p₆ #[p₃, p₄, p₅] with
  | .inl () => IO.println "No witness found"
  | .inr w =>
    let wStr := w.foldl (init := "[\n") (λ str p => str ++ s!" {p},\n")
    IO.println s!"Witness found: {wStr}]"
  return ()
--#eval Polynomial.idealMembership p₆ #[p₃, p₄, p₅]
--#eval Polynomial.divPolys p₆ #[p₃, p₄, p₅]

end VerusLean.Tactic.Modular
